Create test_review
Ayahviramempesonah/JAVA_BASIC_INTLJJ pull request #8
Opened 2021-09-17 15:43 UTC by sarwoTamvan

coba

2021-09-17 15:49 UTC, Ayahviramempesonah commented on test_review
> +test for review
coba di kondisikan saja

2021-09-17 15:50 UTC, sarwoTamvan commented on test_review
> +test for review
coba di cek lagi

2021-09-17 15:52 UTC, Ayahviramempesonah reviewed
gedeg w

2021-09-17 15:52 UTC, Ayahviramempesonah commented on test_review
> +test for review
yah ngeyel dibilangin

2021-09-17 15:54 UTC, Ayahviramempesonah requested changes

2021-09-17 15:54 UTC, Ayahviramempesonah commented on test_review
> +test for review
pokonya harus perbaikan

2021-09-20 04:16 UTC, merged

2021-09-20 04:16 UTC, Ayahviramempesonah commented
code review diterima